#!/bin/sh

apt-get update
apt-get upgrade -y --show-upgraded
apt-get install -y sudo apt-get install libxft-dev libxinerama-dev libpango1.0-dev

wget -c https://github.com/DaveDavenport/rofi/releases/download/0.15.4/rofi-0.15.4.tar.gz
tar -xzvf rofi-0.15.4.tar.gz
cd rofi-0.15.4

autoreconf -i
./configure
make && make install
 
apt-get autoclean -y
apt-get clean -y
apt-get autoremove -y
