#!/bin/sh

# Origin from: https://www.v2ex.com/t/185343#reply43

t () {
  wget -qO- "http://fanyi.youdao.com/openapi.do?keyfrom=leecade&key=54015339&type=data&doctype=json&version=1.1&q=$1" | grep --color=auto -oP '(?<="explains":\[")[^"]*'
}

t $*
